version: '3'

services:
  backend:
    image: munji-back
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: munji-back-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend/assets:/app/assets
      - ./backend/subtitles:/app/subtitles
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video]
  
  frontend:
    depends_on:
      - backend
    image: munji-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: munji-front-container
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src/components:/app/src/components
