version: '3'

services:
  backend:
    image: munji-back
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: munji-back-container
    ports:
      - "8000:8000"
  frontend:
    depends_on:
      - backend
    image: munji-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: munji-front-container
    ports:
      - "8080:8080"
